In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df_train=pd.read_csv('train.csv')

In [ ]:
df_test=pd.read_csv('test.csv')

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB


In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB


In [ ]:
df_train.shape

(4209, 378)

In [ ]:
df_test.shape

(4209, 377)

In [ ]:
df_train.head()

ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 378 columns]

In [ ]:
df_test.head()

ID  X0 X1  X2 X3 X4 X5 X6  ... X377  X378  X379  X380  X382  X383  X384  X385
0   1  az  v   n  f  d  t  a  ...    0     1     0     0     0     0     0     0
1   2   t  b  ai  a  d  b  g  ...    1     0     0     0     0     0     0     0
2   3  az  v  as  f  d  a  j  ...    0     1     0     0     0     0     0     0
3   4  az  l   n  f  d  z  l  ...    0     1     0     0     0     0     0     0
4   5   w  s  as  c  d  y  i  ...    0     0     0     0     0     0     0     0

[5 rows x 377 columns]

In [ ]:
df_train.describe()

ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

In [ ]:
df_train.y.describe()

count    4209.000000
mean      100.669318
std        12.679381
min        72.110000
25%        90.820000
50%        99.150000
75%       109.010000
max       265.320000
Name: y, dtype: float64

In [ ]:
df_train.dtypes.value_counts()

int64      369
object       8
float64      1
dtype: int64

In [ ]:
df_test.dtypes.value_counts()

int64     369
object      8
dtype: int64

In [ ]:
df_test.describe()

ID          X10  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4211.039202     0.019007  ...     0.000713     0.001663
std    2423.078926     0.136565  ...     0.026691     0.040752
min       1.000000     0.000000  ...     0.000000     0.000000
25%    2115.000000     0.000000  ...     0.000000     0.000000
50%    4202.000000     0.000000  ...     0.000000     0.000000
75%    6310.000000     0.000000  ...     0.000000     0.000000
max    8416.000000     1.000000  ...     1.000000     1.000000

[8 rows x 369 columns]

In [ ]:
df_test.dtypes.value_counts()

int64     369
object      8
dtype: int64

In [ ]:
cat_feature = df_train.select_dtypes(include='object')
cat_feature

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

# First,check the original variance of all the features in the train dataset and store it to new object

In [ ]:
pd.DataFrame(df_train.var(axis=0),columns=['Variance'])
df_train_var=pd.DataFrame(df_train.var(axis=0),columns=['Variance'])
df_train_var

Variance
ID    5.941936e+06
y     1.607667e+02
X10   1.313092e-02
X11   0.000000e+00
X12   6.945713e-02
...            ...
X380  8.014579e-03
X382  7.546747e-03
X383  1.660732e-03
X384  4.750593e-04
X385  1.423823e-03

[370 rows x 1 columns]

#Second, define a function to remove the features of train dataset with zero variance

In [ ]:
 def remove_variables(df):
    df_var=pd.DataFrame(df.var(axis=0),columns=['Variance'])
    return((df_var[df_var.Variance==0]))

In [ ]:
# Call the function to return the train dataset features having zero variance.
remove_variables(df_train)

Variance
X11        0.0
X93        0.0
X107       0.0
X233       0.0
X235       0.0
X268       0.0
X289       0.0
X290       0.0
X293       0.0
X297       0.0
X330       0.0
X347       0.0

# Remove the features with 0 variance from train dataset and store the data in the new object

In [ ]:
df_train_new=df_train.drop(columns=df_train_var[df_train_var.Variance==0].index)
    
## train_original_modified= train_original.drop(columns=train_original_var[train_original_var.Variance==0].index)

In [ ]:
df_train_new.head()

ID       y  X0 X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
0   0  130.81   k  v  at  a  d  ...    0    0    0     0     0     0     0
1   6   88.53   k  t  av  e  d  ...    0    0    0     0     0     0     0
2   7   76.26  az  w   n  c  d  ...    0    0    0     1     0     0     0
3   9   80.62  az  t   n  f  d  ...    0    0    0     0     0     0     0
4  13   78.02  az  v   n  f  d  ...    0    0    0     0     0     0     0

[5 rows x 366 columns]

In [ ]:
# Print the original and modified shape of the train dataset
print('Shape of original train dataset is:', df_train.shape)
print('\nShape of modified train dataset after removing features having zero variance is:', df_train_new.shape)

Shape of original train dataset is: (4209, 378)

Shape of modified train dataset after removing features having zero variance is: (4209, 366)


In [ ]:
# First,check the original variance of all the features in the test dataset and store it to new object
df_test_var=pd.DataFrame(df_test.var(axis=0),columns=['Variance'])
df_test_var

Variance
ID    5.871311e+06
X10   1.865006e-02
X11   2.375861e-04
X12   6.885074e-02
X13   5.734498e-02
...            ...
X380  8.014579e-03
X382  8.715481e-03
X383  4.750593e-04
X384  7.124196e-04
X385  1.660732e-03

[369 rows x 1 columns]

In [ ]:
# Call the function to return the test dataset features having zero variance.
remove_variables(df_test)

Variance
X257       0.0
X258       0.0
X295       0.0
X296       0.0
X369       0.0

In [ ]:
# In test dataset, remove the same features of train dataset having 0 variance.
##df_test_new= df_test.drop(columns=['X11', 'X93', 'X107','X233', 'X235', 'X268', 'X289', 'X290', 'X293','X297','X330','X347'])
df_test_new=df_test.drop(columns=df_test_var[df_test_var.Variance==0].index)

In [ ]:
df_test_new.head()

ID  X0 X1  X2 X3 X4 X5 X6  ... X377  X378  X379  X380  X382  X383  X384  X385
0   1  az  v   n  f  d  t  a  ...    0     1     0     0     0     0     0     0
1   2   t  b  ai  a  d  b  g  ...    1     0     0     0     0     0     0     0
2   3  az  v  as  f  d  a  j  ...    0     1     0     0     0     0     0     0
3   4  az  l   n  f  d  z  l  ...    0     1     0     0     0     0     0     0
4   5   w  s  as  c  d  y  i  ...    0     0     0     0     0     0     0     0

[5 rows x 372 columns]

In [ ]:
# Print the original and modified shape of the test dataset
print('Shape of original train dataset is:', df_test.shape)
print('\nShape of modified train dataset after removing features having zero variance is:', df_test_new.shape)

Shape of original train dataset is: (4209, 377)

Shape of modified train dataset after removing features having zero variance is: (4209, 372)


# Searching for null values
# Creating a function for the same
# There are no missin values

In [ ]:
def detect(df):
    if df.isnull().any().any():
        print("Yes")
    else:
        print("No")

detect(df_train_new)
detect(df_test_new)

No
No


In [ ]:
# I will drop this ID variable because they seem very random
# Also remove Y from Training dataset 
df_train_modified=df_train_new.drop(columns=['ID','y'])
df_train_modified.shape

(4209, 364)

# perform label encoder/one hot encoding for the categories features

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
cat_feature = df_train.select_dtypes(include='object')
cat_feature

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [ ]:
for i in df_train_modified.columns:
    if i in cat_feature.columns:
        enc = LabelEncoder()
        df_train_modified[i]=enc.fit_transform(df_train_modified[i])

In [ ]:
df_train_modified.head()

X0  X1  X2  X3  X4  X5  X6  ...  X378  X379  X380  X382  X383  X384  X385
0  32  23  17   0   3  24   9  ...     0     0     0     0     0     0     0
1  32  21  19   4   3  28  11  ...     0     0     0     0     0     0     0
2  20  24  34   2   3  27   9  ...     0     0     0     1     0     0     0
3  20  21  34   5   3  27  11  ...     0     0     0     0     0     0     0
4  20  23  34   5   3  12   3  ...     0     0     0     0     0     0     0

[5 rows x 364 columns]

# perform label encoder/one hot encoding for the categories features in Test_Data

In [ ]:
# I will drop this ID variable because they seem very random
df_test_modified=df_test_new.drop(columns=['ID'])
df_test_modified.shape

(4209, 371)

In [ ]:
df_test_modified.head()

X0 X1  X2 X3 X4 X5 X6 X8  ...  X377  X378  X379  X380  X382  X383  X384  X385
0  az  v   n  f  d  t  a  w  ...     0     1     0     0     0     0     0     0
1   t  b  ai  a  d  b  g  y  ...     1     0     0     0     0     0     0     0
2  az  v  as  f  d  a  j  j  ...     0     1     0     0     0     0     0     0
3  az  l   n  f  d  z  l  n  ...     0     1     0     0     0     0     0     0
4   w  s  as  c  d  y  i  m  ...     0     0     0     0     0     0     0     0

[5 rows x 371 columns]

In [ ]:
cat_feature1 = df_test.select_dtypes(include='object')
cat_feature1

X0  X1  X2 X3 X4  X5 X6 X8
0     az   v   n  f  d   t  a  w
1      t   b  ai  a  d   b  g  y
2     az   v  as  f  d   a  j  j
3     az   l   n  f  d   z  l  n
4      w   s  as  c  d   y  i  m
...   ..  ..  .. .. ..  .. .. ..
4204  aj   h  as  f  d  aa  j  e
4205   t  aa  ai  d  d  aa  j  y
4206   y   v  as  f  d  aa  d  w
4207  ak   v  as  a  d  aa  c  q
4208   t  aa  ai  c  d  aa  g  r

[4209 rows x 8 columns]

In [ ]:
for i1 in df_test_modified.columns:
    if i1 in cat_feature1.columns:
        enc1 = LabelEncoder()
        df_test_modified[i1]=enc1.fit_transform(df_test_modified[i1])

In [ ]:
df_train_modified.head()

X0  X1  X2  X3  X4  X5  X6  ...  X378  X379  X380  X382  X383  X384  X385
0  32  23  17   0   3  24   9  ...     0     0     0     0     0     0     0
1  32  21  19   4   3  28  11  ...     0     0     0     0     0     0     0
2  20  24  34   2   3  27   9  ...     0     0     0     1     0     0     0
3  20  21  34   5   3  27  11  ...     0     0     0     0     0     0     0
4  20  23  34   5   3  12   3  ...     0     0     0     0     0     0     0

[5 rows x 364 columns]

##Trying to reduce dimensions using PCA in Trian_Data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()
scaler.fit(df_train_modified)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaled_data=scaler.transform(df_train_modified)

In [ ]:
scaled_data

array([[ 0.16301209,  1.39348787, -0.02812155, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 0.16301209,  1.15902093,  0.15538793, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-0.71055977,  1.51072134,  1.53170902, ..., -0.04081511,
        -0.02180363, -0.03778296],
       ...,
       [-1.58413164,  1.39348787,  1.89872798, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [-1.51133398,  0.924554  ,  0.70591637, ..., -0.04081511,
        -0.02180363, -0.03778296],
       [ 1.18217927,  0.924554  , -1.31268791, ..., -0.04081511,
        -0.02180363, -0.03778296]])

In [ ]:
from sklearn.decomposition import PCA
pca_model=PCA()
pca_model.fit(scaled_data)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca_model.explained_variance_ratio_

array([6.89266892e-02, 5.68841213e-02, 4.53745695e-02, 3.42677135e-02,
       3.26430877e-02, 3.16266067e-02, 2.86252442e-02, 2.12375123e-02,
       1.97041337e-02, 1.78319550e-02, 1.64006646e-02, 1.56428622e-02,
       1.46274226e-02, 1.44833491e-02, 1.34828580e-02, 1.29516175e-02,
       1.24383219e-02, 1.17310333e-02, 1.12105051e-02, 1.07727793e-02,
       9.92512898e-03, 9.69449157e-03, 9.42523076e-03, 9.09867975e-03,
       8.74223908e-03, 8.43069482e-03, 7.90204943e-03, 7.63217614e-03,
       7.33541876e-03, 7.14905572e-03, 6.92957269e-03, 6.76677298e-03,
       6.52534438e-03, 6.41494089e-03, 6.22692040e-03, 5.99196153e-03,
       5.88086185e-03, 5.74693562e-03, 5.63702738e-03, 5.53409616e-03,
       5.50641149e-03, 5.40082599e-03, 5.33910600e-03, 5.24611598e-03,
       5.10194247e-03, 5.03232420e-03, 4.95885463e-03, 4.72691565e-03,
       4.64475228e-03, 4.56521484e-03, 4.39624472e-03, 4.32947533e-03,
       4.30322432e-03, 4.23762131e-03, 4.20211958e-03, 4.15473420e-03,
      

In [ ]:
pca_model.explained_variance_ratio_.cumsum()*100

array([  6.89266892,  12.58108105,  17.11853799,  20.54530934,
        23.80961811,  26.97227878,  29.83480321,  31.95855443,
        33.9289678 ,  35.7121633 ,  37.35222976,  38.91651598,
        40.37925823,  41.82759314,  43.17587894,  44.47104068,
        45.71487287,  46.8879762 ,  48.00902671,  49.08630463,
        50.07881753,  51.04826669,  51.99078977,  52.90065774,
        53.77488165,  54.61795113,  55.40815607,  56.17137369,
        56.90491556,  57.61982114,  58.3127784 ,  58.9894557 ,
        59.64199014,  60.28348423,  60.90617627,  61.50537242,
        62.09345861,  62.66815217,  63.23185491,  63.78526452,
        64.33590567,  64.87598827,  65.40989887,  65.93451047,
        66.44470472,  66.94793714,  67.4438226 ,  67.91651416,
        68.38098939,  68.83751088,  69.27713535,  69.71008288,
        70.14040531,  70.56416744,  70.9843794 ,  71.39985282,
        71.80655236,  72.21001511,  72.6018891 ,  72.99063619,
        73.37239551,  73.74795561,  74.12039567,  74.48

In [ ]:
pca_model.components_

array([[-5.35850147e-02,  3.02768146e-02,  7.67089079e-02, ...,
         2.54830761e-03, -1.03542621e-03, -3.83323362e-03],
       [-4.40293464e-02,  7.64543717e-02,  3.03300345e-02, ...,
        -6.26757593e-03, -1.08513170e-04,  2.65683265e-03],
       [-7.54999549e-02,  1.10395307e-01, -1.18728567e-02, ...,
        -6.28244169e-03,  3.31178413e-03,  1.49452025e-02],
       ...,
       [ 0.00000000e+00, -3.55906643e-18, -8.60657269e-17, ...,
         3.55618313e-17,  2.86229374e-17,  1.37926187e-02],
       [ 0.00000000e+00,  1.30483731e-16, -1.38789874e-16, ...,
        -5.29090660e-17, -4.51028104e-17, -1.80900240e-01],
       [ 0.00000000e+00, -1.79977561e-17, -1.45053380e-16, ...,
        -4.42354486e-17,  5.20417043e-17, -1.41561710e-02]])

In [ ]:
pca_model=PCA(n_components=120)

In [ ]:
pca_model.fit(df_train_modified)

PCA(copy=True, iterated_power='auto', n_components=120, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca_model.transform(df_train_modified)

array([[ 6.14764599e-01, -1.33009451e-01,  1.56244600e+01, ...,
         4.10784047e-01, -1.94194710e-01, -3.10548751e-01],
       [ 5.65406646e-01,  1.56033294e+00,  1.79095812e+01, ...,
         1.65040932e-01, -1.32602535e-01,  5.66309911e-02],
       [ 1.62017126e+01,  1.22928463e+01,  1.76335395e+01, ...,
         1.01927148e-02, -1.79062029e-01, -4.80508612e-01],
       ...,
       [ 2.90046604e+01,  1.48609053e+01, -7.75333217e+00, ...,
         7.42541786e-02,  3.93337196e-04, -2.40796294e-03],
       [ 2.29724217e+01,  1.68482437e+00, -9.03124768e+00, ...,
         5.71076514e-02, -7.38170742e-02, -1.06536442e-01],
       [-1.72830483e+01, -9.95198181e+00, -3.71935977e+00, ...,
        -2.20954535e-02, -7.49003411e-02, -8.47378880e-02]])

In [ ]:
df_train_modified_pca=pd.DataFrame(pca_model.transform(df_train_modified))

In [ ]:
pca_model.explained_variance_ratio_.cumsum()*100

array([38.33478209, 59.72281468, 72.98468058, 84.81132306, 94.01733148,
       95.60793581, 96.35247553, 96.7861768 , 97.08019744, 97.32199362,
       97.55848165, 97.76171025, 97.92891403, 98.07702523, 98.20572761,
       98.30930287, 98.40503629, 98.49473266, 98.57330141, 98.6442734 ,
       98.7087116 , 98.7710929 , 98.82955487, 98.88079916, 98.92927696,
       98.97258751, 99.01398124, 99.05174538, 99.08860662, 99.12421407,
       99.15716723, 99.18861562, 99.21858587, 99.24685259, 99.27366927,
       99.29852366, 99.32066217, 99.34211583, 99.36284049, 99.38249029,
       99.40120321, 99.41907739, 99.43666419, 99.45411254, 99.47118468,
       99.48649031, 99.50143525, 99.51581196, 99.52995727, 99.54378483,
       99.55713062, 99.57010625, 99.58270393, 99.59463721, 99.60610457,
       99.61691636, 99.62761471, 99.63790823, 99.64804337, 99.6579137 ,
       99.66721827, 99.67629323, 99.68498626, 99.69360147, 99.70155283,
       99.70935019, 99.71695557, 99.72445086, 99.73152755, 99.73

In [ ]:
pca_model.components_

array([[-9.31138471e-01,  2.45494127e-01,  2.57713643e-01, ...,
         2.84628944e-06, -9.56497803e-06, -2.86842355e-05],
       [ 2.63046285e-01, -1.92186472e-02,  9.59720661e-01, ...,
        -9.23858305e-05, -5.16075133e-07, -1.32382564e-05],
       [ 1.40346165e-01,  5.51248020e-01,  2.15461586e-03, ...,
        -1.13659802e-04,  4.64816456e-05,  1.61546453e-04],
       ...,
       [-4.05666824e-04, -3.54104726e-03,  2.19906549e-03, ...,
        -8.41804954e-03, -1.22953324e-04,  3.73764086e-02],
       [-6.18681159e-04,  1.53801497e-03, -1.82350990e-04, ...,
         1.99845418e-02, -1.42710990e-03,  3.90570843e-02],
       [-5.99174470e-04, -4.83718449e-04,  1.85751501e-04, ...,
         1.14359755e-02,  1.17596534e-02, -7.96573549e-03]])

In [ ]:
df_train_modified_pca.head()

0          1          2    ...       117       118       119
0   0.614765  -0.133009  15.624460  ...  0.410784 -0.194195 -0.310549
1   0.565407   1.560333  17.909581  ...  0.165041 -0.132603  0.056631
2  16.201713  12.292846  17.633540  ...  0.010193 -0.179062 -0.480509
3  16.149998  13.535419  14.898695  ... -0.601659  0.411451 -0.142541
4  16.459103  13.175004   4.403096  ... -0.059839 -0.070311 -0.312436

[5 rows x 120 columns]

##Trying to reduce dimensions using PCA in Test_Data

In [ ]:
scaler1=StandardScaler()
scaler1.fit(df_test_modified)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
scaled_data1=scaler1.transform(df_test_modified)

In [ ]:
scaled_data1

array([[-0.62521149,  1.39576032,  1.58606761, ..., -0.02180363,
        -0.02670705, -0.04081511],
       [ 0.75460919, -0.94519929, -0.95644521, ..., -0.02180363,
        -0.02670705, -0.04081511],
       [-0.62521149,  1.39576032, -0.07634462, ..., -0.02180363,
        -0.02670705, -0.04081511],
       ...,
       [ 1.08313793,  1.39576032, -0.07634462, ..., -0.02180363,
        -0.02670705, -0.04081511],
       [-1.54509194,  1.39576032, -0.07634462, ..., -0.02180363,
        -0.02670705, -0.04081511],
       [ 0.75460919, -1.17929525, -0.95644521, ..., -0.02180363,
        -0.02670705, -0.04081511]])

In [ ]:
pca_model1=PCA()
pca_model1.fit(scaled_data1)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca_model1.explained_variance_ratio_

array([6.91362017e-02, 5.45766166e-02, 4.65903155e-02, 3.38722867e-02,
       3.17405858e-02, 3.07680312e-02, 2.74003718e-02, 2.07707974e-02,
       1.85495894e-02, 1.69114131e-02, 1.61385195e-02, 1.59285309e-02,
       1.45058622e-02, 1.34782960e-02, 1.31215709e-02, 1.24326744e-02,
       1.20235224e-02, 1.18296151e-02, 1.09313194e-02, 1.03830506e-02,
       1.00239473e-02, 9.76710651e-03, 9.10835143e-03, 9.00475635e-03,
       8.75810880e-03, 8.32992473e-03, 8.28711277e-03, 7.60688983e-03,
       7.27811105e-03, 7.11621426e-03, 7.01961148e-03, 6.85338467e-03,
       6.71951004e-03, 6.65030111e-03, 6.45454838e-03, 6.18059606e-03,
       6.09236310e-03, 6.02179340e-03, 5.82659850e-03, 5.80678975e-03,
       5.70883577e-03, 5.40591739e-03, 5.26613212e-03, 5.17182392e-03,
       5.12042729e-03, 4.98704940e-03, 4.88584729e-03, 4.68619404e-03,
       4.58467406e-03, 4.52010424e-03, 4.46171987e-03, 4.35924816e-03,
       4.28754752e-03, 4.18810374e-03, 4.14476850e-03, 4.10322865e-03,
      

In [ ]:
pca_model1.explained_variance_ratio_.cumsum()*100

array([  6.91362017,  12.37128183,  17.03031338,  20.41754205,
        23.59160063,  26.66840376,  29.40844094,  31.48552068,
        33.34047962,  35.03162093,  36.64547288,  38.23832597,
        39.68891219,  41.03674179,  42.34889888,  43.59216632,
        44.79451856,  45.97748006,  47.070612  ,  48.10891706,
        49.1113118 ,  50.08802245,  50.99885759,  51.89933323,
        52.77514411,  53.60813658,  54.43684786,  55.19753684,
        55.92534794,  56.63696937,  57.33893052,  58.02426898,
        58.69621999,  59.3612501 ,  60.00670494,  60.62476454,
        61.23400085,  61.83618019,  62.41884004,  62.99951902,
        63.5704026 ,  64.11099433,  64.63760755,  65.15478994,
        65.66683267,  66.16553761,  66.65412234,  67.12274174,
        67.58120915,  68.03321957,  68.47939156,  68.91531637,
        69.34407112,  69.7628815 ,  70.17735835,  70.58768121,
        70.9832539 ,  71.37710285,  71.76180654,  72.14418445,
        72.51955588,  72.89236546,  73.25980433,  73.62

In [ ]:
pca_model1.components_

array([[-5.18995962e-02,  3.53804644e-02,  7.32078923e-02, ...,
         2.49118878e-03, -8.76879806e-04, -3.77443326e-03],
       [-4.69908839e-02,  8.63025855e-02,  2.64420060e-02, ...,
        -3.41800079e-03, -1.65569590e-03,  4.04611867e-03],
       [-7.66806032e-02,  1.05884084e-01,  9.06838579e-04, ...,
        -4.34975301e-03,  1.04152737e-03,  1.41745930e-02],
       ...,
       [ 0.00000000e+00,  2.26834857e-16, -2.22867097e-17, ...,
        -3.90312782e-17,  4.71627945e-17,  1.60270267e-01],
       [-0.00000000e+00,  1.94328942e-16,  4.62773446e-16, ...,
         7.28583860e-17, -1.21430643e-17, -1.26587998e-01],
       [-0.00000000e+00,  1.87350135e-16, -2.24181779e-16, ...,
        -6.85215773e-17,  3.46944695e-18, -2.16240374e-01]])

In [ ]:
pca_model1=PCA(n_components=120)

In [ ]:
pca_model1.fit(df_test_modified)

PCA(copy=True, iterated_power='auto', n_components=120, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca_model1.transform(df_test_modified)

array([[ 1.45833617e+01,  1.41667255e+01,  1.35385760e+01, ...,
        -3.44980239e-01, -1.56370636e-01, -1.03757715e-01],
       [-1.52516126e+01, -7.73675622e+00, -7.45495093e+00, ...,
        -2.28079752e-01,  4.33437881e-02, -2.81997466e-02],
       [ 1.18564648e+01, -1.68017313e+00, -9.98961457e+00, ...,
         3.16965066e-02, -1.53688417e-01, -7.24150566e-02],
       ...,
       [-1.34464401e+01,  3.28858211e+00, -6.85236379e+00, ...,
        -1.13644976e-02, -1.71625205e-02,  8.48894136e-02],
       [ 2.49261231e+01, -4.89888665e+00, -1.01694102e+01, ...,
         9.14398554e-03,  1.96809465e-02, -1.97367741e-02],
       [-1.53843098e+01, -7.73425450e+00, -1.54930106e+01, ...,
        -2.41281163e-02, -6.19042790e-02,  2.74435912e-02]])

In [ ]:
df_test_modified_pca=pd.DataFrame(pca_model1.transform(df_test_modified))

In [ ]:
pca_model1.explained_variance_ratio_.cumsum()*100

array([43.51510223, 61.18599906, 74.83229129, 85.81020294, 94.43241076,
       95.86637291, 96.58933861, 96.99618142, 97.27018856, 97.49830057,
       97.71982601, 97.90254661, 98.06067143, 98.19911155, 98.31990195,
       98.41961868, 98.50879818, 98.59125895, 98.66358875, 98.7291745 ,
       98.79156716, 98.84931011, 98.90352573, 98.95270706, 98.99619138,
       99.03752926, 99.07581726, 99.11205359, 99.1469621 , 99.18112213,
       99.21263081, 99.2414459 , 99.26967579, 99.29622187, 99.32012066,
       99.34370665, 99.36556998, 99.38654992, 99.40573314, 99.42346248,
       99.44077342, 99.45786212, 99.4739514 , 99.48962157, 99.50446839,
       99.51847023, 99.53234343, 99.54590676, 99.55908545, 99.57207793,
       99.58440143, 99.59633028, 99.60764706, 99.61864173, 99.62957884,
       99.63949125, 99.64927595, 99.65886795, 99.66799172, 99.67704164,
       99.68575973, 99.69435502, 99.70264727, 99.71071937, 99.71833488,
       99.72567575, 99.73300132, 99.74005956, 99.74673512, 99.75

In [ ]:
pca_model1.components_

array([[-9.52702651e-01,  2.25108220e-01,  1.90409775e-01, ...,
         2.54757881e-05, -2.47982573e-05, -3.48543132e-05],
       [ 2.11537062e-01,  6.76982980e-02,  9.72085703e-01, ...,
        -1.99395073e-05,  4.39410221e-06,  1.47941205e-06],
       [ 8.21218547e-02,  3.80477190e-01, -3.26335920e-02, ...,
        -3.96735120e-05,  4.29528868e-05,  1.58854133e-04],
       ...,
       [-3.98164362e-04,  1.11015376e-03, -3.36252247e-03, ...,
        -7.26171356e-03, -1.51708346e-02, -2.07653918e-02],
       [-3.61662438e-04,  1.68417208e-03,  5.35385899e-03, ...,
         5.18250249e-03, -2.54876511e-03,  4.56191230e-02],
       [ 7.58382071e-04,  2.16404417e-04,  1.43286167e-03, ...,
         5.49324193e-03,  2.24328170e-02, -4.22238227e-02]])

In [ ]:
df_test_modified_pca.head()

0          1          2    ...       117       118       119
0  14.583362  14.166725  13.538576  ... -0.344980 -0.156371 -0.103758
1 -15.251613  -7.736756  -7.454951  ... -0.228080  0.043344 -0.028200
2  11.856465  -1.680173  -9.989615  ...  0.031697 -0.153688 -0.072415
3  12.606882  13.871583  14.143968  ... -0.517985  0.003854  0.014019
4 -11.897597   2.735944  18.424166  ... -0.070573 -0.130650 -0.118374

[5 rows x 120 columns]

##Building the xgboost model to predict test data

In [ ]:
import xgboost as xgb
from sklearn.metrics import r2_score
from xgboost import XGBRegressor,plot_importance
from sklearn.model_selection import train_test_split

In [ ]:
#xgbModel=XGBRegressor(max_depth=4, min_child_weight=5, reg_lambda=100, gamma = 200)
#xgbModel.fit(x_train,y_train)
#print(xgbModel.score(x_train,y_train))
#print(xgbModel.score(x_test,y_test))



In [ ]:
# Splitting the data by 80/20
#x_train, x_valid, y_train, y_valid = train_test_split(df_train_modified_pca, df_test_modified_pca, test_size = 0.2, random_state = 42)
#x_train,x_test,y_train,y_test=train_test_split(df_train_modified_pca,random_state=10,train_size=0.75)

In [ ]:
#xgbModel=XGBRegressor(max_depth=3, min_child_weight=4, reg_lambda=1000, gamma = 100)

In [ ]:
y_train = df_train['y'].values
y_train

array([130.81,  88.53,  76.26, ..., 109.22,  87.48, 110.85])

In [ ]:
x_train

0          1          2    ...       117       118       119
608   -5.126549   1.138200  -3.006066  ...  0.024363 -0.043208  0.022234
2863  13.548770 -16.124766  -2.385695  ... -0.051165 -0.023295  0.015596
1307  22.913985  16.686196 -10.748903  ...  0.060400 -0.163889  0.051497
241   -7.178711  18.624346  -3.980141  ... -0.028397  0.010521  0.005035
47    -7.270501  17.556428  -3.624411  ... -0.007994  0.003813  0.029669
...         ...        ...        ...  ...       ...       ...       ...
2009  -8.186196  12.205944  12.285562  ...  0.048789  0.073189 -0.068336
1180 -15.036995  -0.489919  -8.311757  ... -0.067382 -0.067250  0.157137
3441  22.623069  15.998752   5.672344  ... -0.049353 -0.003349  0.055346
1344  -0.272827 -13.908414  -8.879767  ...  0.039040 -0.015213 -0.057948
1289 -14.119018  13.590264 -13.412629  ... -0.002196  0.163385 -0.098030

[3156 rows x 120 columns]

In [ ]:
##xgbModel.fit(x_train,y_train)

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df_train_modified_pca,y_train,random_state=10,train_size=0.75)

In [ ]:
xgbModel=XGBRegressor(max_depth=3, min_child_weight=4, reg_lambda=1000, gamma = 100)

In [ ]:
xgbModel.fit(x_train,y_train)

[19:44:55] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=100,
             importance_type='gain', learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=4, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1000, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)

In [ ]:
print(xgbModel.score(x_train,y_train))
print(xgbModel.score(x_test,y_test))

0.5142425830854119
0.48255523817053597


In [ ]:
xgb_feature_imp=(pd.DataFrame(xgbModel.feature_importances_,index=df_test_modified_pca.columns))

In [ ]:
xgb_feature_imp.sort_values(by=0)

0
59  0.000000
85  0.000000
84  0.000000
83  0.000000
82  0.000000
..       ...
7   0.047253
9   0.049590
16  0.059265
0   0.062923
11  0.063454

[120 rows x 1 columns]